### ISSUE TITLE
RPCh v1.0.0

### ISSUE THREAD

**Issue by nionis** [hoprnet/RPCh#16]
### Description

The roadmap to RPCh v1.0.0.

### Relevant issues

- [ ] #17 
- [ ] create RPCh v1.0.0 spec
  - [ ] #20
  - [ ] #21
  - [ ] #23
  - [ ] #22
  - [x] #24
  - [ ] spec addition of Kelvar
- ~[ ] design of RPCh's website (?)~
- [ ] #25
  - should include all tooling required (ex: TS, prettier, etc)
- [ ] divide & conquer (plan with RPCh team who and what is working on)
- [ ] implement RPCh commons
- [ ] implement RPCh SDK
- [ ] implement RPCh adaptors
- [ ] implement RPCh exit
- [ ] implement HOPRd & RPCh docker-compose
- [ ] implement discovery platform & hot wallet functionality
- [ ] integrate with RPC providers

### Possibly blocked by

- core: token and quota-based limited access API, token based access to WS streams
- core: API to create such token ^
- core: spec an encryption mechanism for entry and exit nodes
- core: fix multi-hop rapid message sending
- core: ensure promiscuous strategy is working
- core: access to NR or no NR

### Post v1.0.0

- https://github.com/hoprnet/RPCh/issues/19

### Definition of DONE

We have an official v1.0.0 release accompanied by the relevant SDK/tooling, additionally, we have a working and healthy RPCh network which wallets can use.
