### ISSUE TITLE
RPCh organisation

### ISSUE THREAD

**Issue by nionis** [hoprnet/RPCh#17]
### Description

Tasks required to begin the RPCh team, non-software related.

### Relevant issues

- [ ] create a new GitHub org @mjadach-iv 
  - move RPCh repository
  - move RPCh issues and epics
  - add members into the organization (Steve and Michal admins)
- [ ] document RPCh's processes @nionis 
  - development
  - wallets
  - evaluations
- [ ] onboard RPCh team
  - [x] messaging chat
  - [x] create messaging chat rooms
  - [x] create workspaces group
- [x] specify onboarding details with the existing HOPR team
- [x] creation of meetings
  - [x] epic priorities, sprint retrospective, sprint planning
  - [x] daily syncs
  - [x] HOPR education
  - [ ] Tech mingle call @mjadach-iv 
  - [ ] Steve <> RPCh team 1-1 @nionis 
- [ ] education
  - Ethereum basics
  - RPCh processes once @nionis has committed them
  - RPCh code
  

### Definition of DONE

The RPCh team is ready to start working on the software side of things whilst the underlying organisational processes/tooling have already been set up and understood.
